<a href="https://colab.research.google.com/github/rexian/ML/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensors

In [7]:
import torch
import numpy as np

In [11]:
np1 = np.random.rand(3,4)
np1

array([[0.93086347, 0.81027327, 0.0246976 , 0.83392075],
       [0.57614307, 0.7612818 , 0.3177613 , 0.55462572],
       [0.16621592, 0.29201759, 0.99810142, 0.3127617 ]])

In [12]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.4166,  0.3534, -0.0426,  0.1991],
        [-0.4325,  0.7085, -0.5295, -0.8158],
        [-0.3152,  0.4266, -0.1568,  0.1831]])

In [13]:
tensor_np = torch.from_numpy(np1)
tensor_np

tensor([[0.9309, 0.8103, 0.0247, 0.8339],
        [0.5761, 0.7613, 0.3178, 0.5546],
        [0.1662, 0.2920, 0.9981, 0.3128]], dtype=torch.float64)