<a href="https://colab.research.google.com/github/rexian/ML/blob/main/pytorch/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

my_tensor = torch.tensor([[1,2,3],[4,5,6]])
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64
cpu
torch.Size([2, 3])
False


In [ ]:
x = torch.randn(3 , requires_grad=True)
print(x)

y = x + 2
print(y)

z = y * y * 2
z = z.mean()
print(z)

z.backward()
print(x.grad)

tensor([-0.1265,  0.0422, -0.1212], requires_grad=True)
tensor([1.8735, 2.0422, 1.8788], grad_fn=<AddBackward0>)
tensor(7.4735, grad_fn=<MeanBackward0>)
tensor([2.4980, 2.7229, 2.5050])
